# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [44]:
import pandas as pa
import matplotlib as plot
file_data=pa.read_csv('./data/ccp_current_csv.csv ')
print file_data


                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW        

### 3.1.a  what is its shape and what does that mean?

In [8]:
file_data.size

12555

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [9]:
file_data['QUADRANT'].value_counts()
 

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [21]:
import numpy as np
from numpy import array
a = array( [9,8,7,6] )
b = array([4,5,6,7])
print a+b #operational use
np.add(a,b) ## Using add function

[13 13 13 13]


array([13, 13, 13, 13])

### 3.3.2 subtraction a-b

In [22]:
print a-b ## using '-' operator
np.subtract(a,b) ## using subtract function

[ 5  3  1 -1]


array([ 5,  3,  1, -1])

### 3.3.3 multiplication a*b

In [23]:
print a*b ## using '*' operator
np.multiply(a,b) ## using multiply function

[36 40 42 42]


array([36, 40, 42, 42])

### 3.3.4 divsion a/b

In [24]:
print a/b ## using '/' operator
np.divide(a,b) ## using divide function

[2 1 1 0]


array([2, 1, 1, 0])

### 3.3.5 modulo  a%b

In [25]:
print a%b ## using '%' operator
np.mod(a,b) ## using mod function

[1 3 1 6]


array([1, 3, 1, 6])

### 3.3.6 power  a^b

In [26]:
print a**b ## using '**' operator
np.power(a,b) ## using power function

[  6561  32768 117649 279936]


array([  6561,  32768, 117649, 279936])

## Homework 3.4
Find your own data and load it into a dataframe

I found this dataset interesting because Game of Thrones is one of the hit fantacy show in the television. The dataset contains the collection of all battles in the series.

In [60]:
import pandas as pa
data_frame=pa.read_csv('./data/battles.csv')
data_frame

name  year  battle_number  \
0                          Battle of the Golden Tooth   298              1   
1                         Battle at the Mummer's Ford   298              2   
2                                  Battle of Riverrun   298              3   
3                            Battle of the Green Fork   298              4   
4                       Battle of the Whispering Wood   298              5   
5                                 Battle of the Camps   298              6   
6                                       Sack of Darry   298              7   
7                               Battle of Moat Cailin   299              8   
8                            Battle of Deepwood Motte   299              9   
9                           Battle of the Stony Shore   299             10   
10                         Battle of Torrhen's Square   299             11   
11                               Battle of Winterfell   299             12   
12                           Sack of Torrhen's Square   299             13   
13                                 Sack of Winterfell   299             14   
14                                  Battle of Oxcross   299             15   
15                               Siege of Storm's End   299             16   
16                                Battle of the Fords   299             17   
17                                  Sack of Harrenhal   299             18   
18                                 Battle of the Crag   299             19   
19                           Battle of the Blackwater   299             20   
20                                     Siege of Darry   299             21   
21                               Battle of Duskendale   299             22   
22                       Battle of the Burning Septry   299             23   
23                            Battle of the Ruby Ford   299             24   
24                              Retaking of Harrenhal   299             25   
25                                    The Red Wedding   299             26   
26                                   Siege of Seagard   299             27   
27                             Battle of Castle Black   300             28   
28                                Fall of Moat Cailin   300             29   
29                                   Sack of Saltpans   300             30   
30                         Retaking of Deepwood Motte   300             31   
31                       Battle of the Shield Islands   300             32   
32  Invasion of Ryamsport, Vinetown, and Starfish ...   300             33   
33                        Second Seige of Storm's End   300             34   
34                               Siege of Dragonstone   300             35   
35                                  Siege of Riverrun   300             36   
36                                 Siege of Raventree   300             37   
37                                Siege of Winterfell   300             38   

               attacker_king             defender_king  \
0   Joffrey/Tommen Baratheon                Robb Stark   
1   Joffrey/Tommen Baratheon                Robb Stark   
2   Joffrey/Tommen Baratheon                Robb Stark   
3                 Robb Stark  Joffrey/Tommen Baratheon   
4                 Robb Stark  Joffrey/Tommen Baratheon   
5                 Robb Stark  Joffrey/Tommen Baratheon   
6   Joffrey/Tommen Baratheon                Robb Stark   
7        Balon/Euron Greyjoy                Robb Stark   
8        Balon/Euron Greyjoy                Robb Stark   
9        Balon/Euron Greyjoy                Robb Stark   
10                Robb Stark       Balon/Euron Greyjoy   
11       Balon/Euron Greyjoy                Robb Stark   
12       Balon/Euron Greyjoy       Balon/Euron Greyjoy   
13  Joffrey/Tommen Baratheon                Robb Stark   
14                Robb Stark  Joffrey/Tommen Baratheon   
15         Stannis Baratheon           Renly Baratheon   
16  Joffrey/Tommen B

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [61]:
data_frame.shape ## To know the number of rows and columns

(38, 25)

In [62]:
data_frame.size

950

In [63]:
data_frame.columns ## Provides the columns present in the data frame

Index([u'name', u'year', u'battle_number', u'attacker_king', u'defender_king',
       u'attacker_1', u'attacker_2', u'attacker_3', u'attacker_4',
       u'defender_1', u'defender_2', u'defender_3', u'defender_4',
       u'attacker_outcome', u'battle_type', u'major_death', u'major_capture',
       u'attacker_size', u'defender_size', u'attacker_commander',
       u'defender_commander', u'summer', u'location', u'region', u'note'],
      dtype='object')

In [64]:
data_frame.describe() ## .describe() method provides the statistics of the battle.


year  battle_number  defender_3  defender_4  major_death  \
count   38.000000      38.000000         0.0         0.0    37.000000   
mean   299.105263      19.500000         NaN         NaN     0.351351   
std      0.689280      11.113055         NaN         NaN     0.483978   
min    298.000000       1.000000         NaN         NaN     0.000000   
25%    299.000000      10.250000         NaN         NaN     0.000000   
50%    299.000000      19.500000         NaN         NaN     0.000000   
75%    300.000000      28.750000         NaN         NaN     1.000000   
max    300.000000      38.000000         NaN         NaN     1.000000   

       major_capture  attacker_size  defender_size     summer  
count      37.000000      24.000000      19.000000  37.000000  
mean        0.297297    9942.541667    6428.157895   0.702703  
std         0.463373   20283.092065    6225.182106   0.463373  
min         0.000000      20.000000     100.000000   0.000000  
25%         0.000000    1375.000000    1070.000000   0.000000  
50%         0.000000    4000.000000    6000.000000   1.000000  
75%         1.000000    8250.000000   10000.000000   1.000000  
max         1.000000  100000.000000   20000.000000   1.000000

In [65]:
## Checking for the team size of attackers and defenders.  

if data_frame['attacker_size'].max() > data_frame['attacker_size'].max():
    print "Strong attacker team"
else:
    print "Strong defender team"


Strong defender team


In [66]:
data_frame[['name','attacker_king','defender_king','attacker_outcome','location']][:20] ## Retrieving the first 20 rows of the desired columns

name             attacker_king  \
0      Battle of the Golden Tooth  Joffrey/Tommen Baratheon   
1     Battle at the Mummer's Ford  Joffrey/Tommen Baratheon   
2              Battle of Riverrun  Joffrey/Tommen Baratheon   
3        Battle of the Green Fork                Robb Stark   
4   Battle of the Whispering Wood                Robb Stark   
5             Battle of the Camps                Robb Stark   
6                   Sack of Darry  Joffrey/Tommen Baratheon   
7           Battle of Moat Cailin       Balon/Euron Greyjoy   
8        Battle of Deepwood Motte       Balon/Euron Greyjoy   
9       Battle of the Stony Shore       Balon/Euron Greyjoy   
10     Battle of Torrhen's Square                Robb Stark   
11           Battle of Winterfell       Balon/Euron Greyjoy   
12       Sack of Torrhen's Square       Balon/Euron Greyjoy   
13             Sack of Winterfell  Joffrey/Tommen Baratheon   
14              Battle of Oxcross                Robb Stark   
15           Siege of Storm's End         Stannis Baratheon   
16            Battle of the Fords  Joffrey/Tommen Baratheon   
17              Sack of Harrenhal                Robb Stark   
18             Battle of the Crag                Robb Stark   
19       Battle of the Blackwater         Stannis Baratheon   

               defender_king attacker_outcome          location  
0                 Robb Stark              win      Golden Tooth  
1                 Robb Stark              win     Mummer's Ford  
2                 Robb Stark              win          Riverrun  
3   Joffrey/Tommen Baratheon             loss        Green Fork  
4   Joffrey/Tommen Baratheon              win   Whispering Wood  
5   Joffrey/Tommen Baratheon              win          Riverrun  
6                 Robb Stark              win             Darry  
7                 Robb Stark              win       Moat Cailin  
8                 Robb Stark              win    Deepwood Motte  
9                 Robb Stark              win       Stony Shore  
10       Balon/Euron Greyjoy              win  Torrhen's Square  
11                Robb Stark              win        Winterfell  
12       Balon/Euron Greyjoy              win  Torrhen's Square  
13                Robb Stark              win        Winterfell  
14  Joffrey/Tommen Baratheon              win           Oxcross  
15           Renly Baratheon              win       Storm's End  
16                Robb Stark             loss          Red Fork  
17  Joffrey/Tommen Baratheon              win         Harrenhal  
18  Joffrey/Tommen Baratheon              win              Crag  
19  Joffrey/Tommen Baratheon             loss    King's Landing

In [12]:
data_frame['attacker_outcome'].value_counts()  ## Total number of wins/losses in the battles

win     32
loss     5
Name: attacker_outcome, dtype: int64

In [28]:
data_frame[['attacker_king','defender_king','attacker_outcome']] ## Retrieving attacker_king,defender_king and attacker_outcome columns

attacker_king             defender_king attacker_outcome
0   Joffrey/Tommen Baratheon                Robb Stark              win
1   Joffrey/Tommen Baratheon                Robb Stark              win
2   Joffrey/Tommen Baratheon                Robb Stark              win
3                 Robb Stark  Joffrey/Tommen Baratheon             loss
4                 Robb Stark  Joffrey/Tommen Baratheon              win
5                 Robb Stark  Joffrey/Tommen Baratheon              win
6   Joffrey/Tommen Baratheon                Robb Stark              win
7        Balon/Euron Greyjoy                Robb Stark              win
8        Balon/Euron Greyjoy                Robb Stark              win
9        Balon/Euron Greyjoy                Robb Stark              win
10                Robb Stark       Balon/Euron Greyjoy              win
11       Balon/Euron Greyjoy                Robb Stark              win
12       Balon/Euron Greyjoy       Balon/Euron Greyjoy              win
13  Joffrey/Tommen Baratheon                Robb Stark              win
14                Robb Stark  Joffrey/Tommen Baratheon              win
15         Stannis Baratheon           Renly Baratheon              win
16  Joffrey/Tommen Baratheon                Robb Stark             loss
17                Robb Stark  Joffrey/Tommen Baratheon              win
18                Robb Stark  Joffrey/Tommen Baratheon              win
19         Stannis Baratheon  Joffrey/Tommen Baratheon             loss
20                Robb Stark  Joffrey/Tommen Baratheon              win
21                Robb Stark  Joffrey/Tommen Baratheon             loss
22                       NaN                       NaN              win
23  Joffrey/Tommen Baratheon                Robb Stark              win
24  Joffrey/Tommen Baratheon                       NaN              win
25  Joffrey/Tommen Baratheon                Robb Stark              win
26                Robb Stark  Joffrey/Tommen Baratheon              win
27         Stannis Baratheon              Mance Rayder             loss
28  Joffrey/Tommen Baratheon       Balon/Euron Greyjoy              win
29                       NaN                       NaN              win
30         Stannis Baratheon       Balon/Euron Greyjoy              win
31       Balon/Euron Greyjoy  Joffrey/Tommen Baratheon              win
32       Balon/Euron Greyjoy  Joffrey/Tommen Baratheon              win
33  Joffrey/Tommen Baratheon         Stannis Baratheon              win
34  Joffrey/Tommen Baratheon         Stannis Baratheon              win
35  Joffrey/Tommen Baratheon                Robb Stark              win
36  Joffrey/Tommen Baratheon                Robb Stark              win
37         Stannis Baratheon  Joffrey/Tommen Baratheon              NaN

In [27]:
max_wins = data_frame[data_frame['attacker_outcome'] == "win"] ## Counts the total number of wins by each attacker
max_wins['attacker_king'].value_counts()

Joffrey/Tommen Baratheon    13
Robb Stark                   8
Balon/Euron Greyjoy          7
Stannis Baratheon            2
Name: attacker_king, dtype: int64

In [70]:

max_wins['attacker_king'].value_counts().plot()


In [46]:
## sum of major deaths and major captures occured in each region

data = data_frame.groupby("region").sum()[["major_death", "major_capture"]]
print data

                 major_death  major_capture
region                                     
Beyond the Wall          1.0            1.0
The Crownlands           2.0            1.0
The North                1.0            2.0
The Reach                0.0            0.0
The Riverlands           6.0            6.0
The Stormlands           1.0            0.0
The Westerlands          2.0            1.0
